name: arm64

kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: arm64

node_selector:
  kubernetes.io/arch: arm64

steps:

- name: publish-arm64
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: dkrizic/neos
    tags: [ "${DRONE_COMMIT_SHA:0:7}-linux-arm64" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

